### PR TITLE
Feature/mongodb river

### PR DESCRIPTION
**Pull request by taterbase**

### CODE REVIEW

**Comment by taterbase** [comment]
@gabrielmancini I finally have this working!!! Could you look it over and let me know if anything looks off? I think it is finally ready to be merged in.

**Comment by gabrielmancini** [comment]
\o/ man this is a great news! good job george! i think its every thing woks fine, its a sorrow, take off my authorship, but ok, the important its i can use the mongoosastic on my project and every one can use river to :-D

cheers George u are a great guy!

**Comment by taterbase** [comment]
@gabrielmancini I fixed it!

**Comment by gabrielmancini** [comment]
OMG!!! Thanks!!!! You are the bes George \o/

**Comment by gabrielmancini** [comment]
George how i use this version?

when i run:
  npm install mongoosastic --save

the npm add this on my package.json :
  "mongoosastic": "0.0.11"

this is right?

cheers

**Comment by taterbase** [comment]
Ah! Gabriel, super sorry about that! It is now published.

**Comment by gabrielmancini** [comment]
\o/ !!!!!!!!!!!!

**Pull request merged**
