### PR TITLE
Keeping virtual properties out of the mapping

### PR DESCRIPTION
**Pull request by nadeesha**
When virtual properties are injected to the mapping, serialize.js throws an error: `Cannot read property 'getters' of undefined`

This fix keeps virtual properties out of the cleantree.

Without this fix, any schema indexed with non-indexed virtual properties will throw an exception while being indexed.

### CODE REVIEW

**Comment by taterbase** [comment]
Hey this looks great! Could you write a test for this functionality?

**Comment by nadeesha** [comment]
There you go. Sorry it took a while. I know there's a discussion on supporting virtual properties to be indexed in the future. But till that happens, I guess this would keep indexing without breaking.

**Comment by taterbase** [comment]
So awesome I can't stand it, thanks for updating.

**Comment by taterbase** [comment]
You'll find your changes in `0.2.5`!

**Pull request merged**
