### PR TITLE
Handle existing index

### PR DESCRIPTION
**Pull request by ro-ka**
If an index exists already, just update the mapping and do not try to create again. That would result in an error, that the index is already existing.

Ticket where we talked about this was #22.

### CODE REVIEW

**Comment by jamescarr** [comment]
Thanks!

**Comment by ro-ka** [comment]
No problem. :)

Do you already know when to expect it in npm?

**Comment by jamescarr** [comment]
I'll push it out this evening when I get home

**Comment by ro-ka** [comment]
Nice. Thanks a lot!

**Pull request merged**
