### PR TITLE
expose index refresh

### PR DESCRIPTION
**Pull request by astro**
I need to synchronize upon that. Alternatively, it would help if the ES client was exposed so I could invoke `refresh()` myself.

### CODE REVIEW

**Comment by taterbase** [comment]
This could potentially overwrite a user's own `schema.static.refresh` function. Maybe we can expose it in a better way?

I'm just digging back in to this repo and evaluating our elastical dependency.

**Comment by davidkaneda** [comment]
Just to chime in here — this is a pretty important feature for my app (and would make integration tests a whole lot easier). I'm not quite sure what the right implementation would be, but I can say for me, a way to pass `refresh: true` while adding/saving/removing a document (via the middleware) would be more useful than a static refresh call. I realize we have "es-indexed" callbacks, but I don't believe they are accurate unless you pass `refresh: true` with the call (otherwise, I believe `es-indexed` just means Elasticsearch got the _request_ to re-index).

Currently, I'm including a few tests which, similar the mongoosastic tests, use a timeout of around 1100ms — but I worry TDD fanatics are going to show up at my door with torches and pitchforks any minute.

**Comment by davidkaneda** [comment]
Also, just want to add thanks to @taterbase for the recent dev push this week — looking forward to trying out 0.3.0 soon.

**Comment by davidkaneda** [comment]
Actually, on second thought, static method may be the best/only way I suppose... (and not unprecedented since you're also taking "synchronize", etc). We definitely don't want to _force_ refresh: true on requests, and I don't see any way of getting specific options from a save() call to the middleware. So at the end of the day, I'd say:

``` (coffeescript)
  doc.save -> Entry.refresh -> done()
```

is still better than:

```
  doc.save().exec()
  doc.on 'es-indexed', ->
    setTimeout done, 1100
```

(excuse the coffeescript)

**Comment by taterbase** [comment]
@davidkaneda great input, really appreciate it. And you're right about how we expose synchronize, so this wouldn't exactly be a surprising api addition.

**Pull request merged**
