### PR TITLE
Feature/handle geo_point and multi_field

### PR DESCRIPTION
**Pull request by ro-ka**
Rewrote the mapping generator to first create a clean object with all the necessary information to build the mapping. Afterwards the mapping is build from that clean tree. Makes it clearer how things are handled (I hope so  ;)  ), especially the special cases like date, geo_point and so on.

Then I added the geo_point with lat_lon fields handling. Multi_field and normal geo_point was already working. Tests added, too.

Btw: Had some problems with the indexing of geo_point at first, but that got fixed in one of your last additions. Thanks! It's working perfect now!

### CODE REVIEW

**Comment by jamescarr** [comment]
Thanks! I find the recursive getMapping function a lot easier to follow now... when I first merged it I had to walk through it a bit to understand it better. :)

**Comment by ro-ka** [comment]
Same here, was hard to find out where which case has which data. So I thought cleaning the tree first takes some pain away. ;)

Will it be published soon? Want to use the geo_point. This was my last pull request for now. :)

**Comment by jamescarr** [comment]
I'll push it out now...

**Comment by ro-ka** [comment]
Thanks a lot! :)

**Comment by jamescarr** [comment]
Can you update the readme.md with a description of using geo_point and multi-field?

**Comment by jamescarr** [comment]
FYI, 0.0.10 has been released. :)

**Comment by ro-ka** [comment]
Will do so.  :)

**Comment by ro-ka** [comment]
Will add it tomorrow. No time anymore.

**Pull request merged**
