### PR TITLE
Add the settings to create mapping.

### PR DESCRIPTION
**Pull request by antoineverger**
I did some work related to #117 and #22.

It's the first step to have a better configuration of the index settings. 
On my side, I needed this functionality to define custom analysers for some fields and I didn't want to manually create for all my ES environments the mapping and the settings. To avoid duplication, I created in my Mongoose models a static method to create indexes where I have my settings but a better approach would be to have the settings declared somehow in the Schema description. 

I also modified the README and added a test case (even if, according to me, the tests do not cover a lot except that it's not failing).

Let me know if you have a better approach and then I can improve it

### CODE REVIEW

**Comment by antoineverger** [comment]
The tests are failing because of the timeout for indexing I guess. They run perfectly in a fast local environment or I'm completely wrong.

**Comment by taterbase** [comment]
Oh man nice work! :raised_hands: :raised_hands: :raised_hands:

**Comment by taterbase** [comment]
Changes have been published, new version is `0.5.0`

**Comment by antoineverger** [comment]
As I said @taterbase, if you have any idea how to declare the settings in a better way in the Mongoose Schema or somewhere else, let me know and I will try to work on that. Thank you for the merge !

**Comment by marsanla** [comment]
#110

**Pull request merged**
