### PR TITLE
Add the esTruncate static method to remove all documents from an index

### PR DESCRIPTION
**Pull request by antoineverger**
Hi,

I created a method to remove all documents from an index. The reason why is that I use mongoosastic in one of my projects and in my integration tests, between two test cases, I manually drop all elements of mongodb collections. The problem is that the documents are not deleted from ES mainly because the synchronize method does not empty the index before putting the documents. This static is, according to me, the first step for properly synchronizing data between mongodb and ES. If you are ok with this PR, I will refactor a bit synchronize so that it first truncate the index and then synchronize the elements.

FYI, the new method has its own test file but I didn't include it to the readme.

### CODE REVIEW

**Comment by antoineverger** [comment]
A small up on this PR. Could you have a look please @taterbase ?

**Comment by antoineverger** [comment]
An other addition I did to the library is to pre-process the field before indexing it.

For example : I have a model with a date (day and time) but I only want to index the day and skip the time (for sorting reasons). I have no way to do that (as far as I can see) with the current implementation of the library (tell me please if I'm wrong). A hack solution would be on my model to duplicate my date field and have one with the full datetime and one with the day date and deal with Mongoose hook to handle that but as I said, that's a hack ;)
Let me know if the fix sounds interesting for you and if some changes are needed.

BTW, I added a test in the serialize and I documented it in the mapping options.

Cheers,

Antoine

**Comment by antoineverger** [comment]
Hi, again a small up about this PR. Could you please have a look ?

**Comment by taterbase** [comment]
Yes @antoineverger sorry about the delay. Looking now

**Comment by taterbase** [comment]
This looks good, would you be willing to update the readme with info about the new casting and esTruncate features?

**Comment by antoineverger** [comment]
Oops, I thought I updated the README but I didn't. I will do it now.

**Comment by antoineverger** [comment]
I added a short documentation about truncate (not so much to say about it!) and the documentation for the cast method was already there (cf. https://github.com/antoineverger/mongoosastic/blob/master/readme.md#mapping-options)

**Comment by taterbase** [comment]
:+1:

**Comment by taterbase** [comment]
Up on npm as version `0.6.0`

**Comment by antoineverger** [comment]
Great George ! Thanks !

**Pull request merged**
